// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// // ignore: depend_on_referenced_packages
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCpT_-qmYv7bdKogKPz8BLATKqJMCmvwrQ',
//     appId: '1:63746941390:web:d33a6eac146a4256cb4b9f',
//     messagingSenderId: '63746941390',
//     projectId: 'cloth-selling-app',
//     authDomain: 'cloth-selling-app.firebaseapp.com',
//     storageBucket: 'cloth-selling-app.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAkzHdMu2OU98NHMnQ3dIFr60TyBu6DWxU',
//     appId: '1:63746941390:android:6f17a6b1ac8ea190cb4b9f',
//     messagingSenderId: '63746941390',
//     projectId: 'cloth-selling-app',
//     storageBucket: 'cloth-selling-app.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDmFvzyDUDAODHAdoBVjfTKxwuFGqQG9ZM',
//     appId: '1:63746941390:ios:31ab8dd1f6d0ae66cb4b9f',
//     messagingSenderId: '63746941390',
//     projectId: 'cloth-selling-app',
//     storageBucket: 'cloth-selling-app.appspot.com',
//     iosClientId: '63746941390-va85sflksl52gdspem9ifr1prqbnb29u.apps.googleusercontent.com',
//     iosBundleId: 'com.example.clothSellingApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDmFvzyDUDAODHAdoBVjfTKxwuFGqQG9ZM',
//     appId: '1:63746941390:ios:31ab8dd1f6d0ae66cb4b9f',
//     messagingSenderId: '63746941390',
//     projectId: 'cloth-selling-app',
//     storageBucket: 'cloth-selling-app.appspot.com',
//     iosClientId: '63746941390-va85sflksl52gdspem9ifr1prqbnb29u.apps.googleusercontent.com',
//     iosBundleId: 'com.example.clothSellingApp',
//   );
// }
